name: photo_manager
description: You can scan photos and albums. Only api, not have ui. you can use the api to create your image picker. or use photo
version: 0.5.8
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: top.kikt.imagescanner
        pluginClass: ImageScannerPlugin
      ios:
        pluginClass: ImageScannerPlugin
      macos:
        pluginClass: ImageScannerPlugin
